mqtt:
  broker:
    url: tcp://localhost:1883
  username: username  # Если не требуется, оставьте пустым
  password: password  # Если не требуется, оставьте пустым
  qos: 1  # Опционально, QoS по умолчанию
  consumerTimeout: 5000