mqtt:
  broker:
    url: ssl://localhost:8883
    username: ADMIN  # Если не требуется, оставьте пустым
    password: 1234  # Если не требуется, оставьте пустым
  ssl:
    insecure: true
  qos: 1  # Опционально, QoS по умолчанию
common:
  checkNotDeliveredTimeout: 120000
  mqttWaitResponseTimeout: 60000
  sendMessagePeriod: 1000
  consumerTimeout: 1000
  messageSendTimeCash :
    collectorRunPeriod : 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/duster
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create